# Generated by Django 5.2.12 on 2026-03-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='addressLine1',
            new_name='addressline1',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='addressLine2',
            new_name='addressline2',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='addressLine3',
            new_name='addressline3',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='addressLine1',
            new_name='addressline1',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='addressLine2',
            new_name='addressline2',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='addressLine3',
            new_name='addressline3',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.FileField(blank=True, default='no_user.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.FileField(blank=True, default='no_user.png', null=True, upload_to='images'),
        ),
    ]
