# Generated by Django 5.2.12 on 2026-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
