# Generated by Django 5.2.12 on 2026-06-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_checkout_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checkoutproducts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
