# Generated by Django 5.2.12 on 2026-06-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_checkout_id_alter_checkoutproducts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
